### ISSUE TITLE
运行服务器后没有CSS样式

### ISSUE THREAD

**Issue by JasonLaii** [lentoo/vue-cli-ssr-example#11]
你好，我根据你的博客文章来改写我之前写的浏览器渲染vue的项目，但是用SSR渲染后CSS样式全部消失了，请问如何才能在SSR渲染时显示我之前写的CSS样式呢？

**Comment by lentoo** [comment]
不清楚你的问题，有 demo 看看吗

**Comment by JasonLaii** [comment]
> 不清楚你的问题，有 demo 看看吗

比如说一个在浏览器渲染里我一个组件得样式是在组件内得sytle里面写的，
在SSR渲染里样式也是在style里头但是样式就不显示了

**Comment by lentoo** [comment]
你可以clone一下我的demo试试看
