### ISSUE TITLE
build:win脚本只能在windows系统上运行，可以提供在linux和mac上的脚本吗

### ISSUE THREAD

**Issue by zhanghanbing1998** [lentoo/vue-cli-ssr-example#14]
build:win脚本只能在windows系统上运行，可以提供在linux和mac上的脚本吗，我开发使用的是mac系统，从而在mac上脚本无法运行，服务器是linux系统，希望能给出能在mac和linux上运行的脚本，O(∩_∩)O谢谢！

**Comment by dingchenaobo** [comment]
"build:win": "npm run build:server && mv dist/vue-ssr-server-bundle.json bundle && npm run build:client && mv bundle dist/vue-ssr-server-bundle.json"

**Comment by zhanghanbing1998** [comment]
> ```
> "build:win": "npm run build:server && mv dist/vue-ssr-server-bundle.json bundle && npm run build:client && mv bundle dist/vue-ssr-server-bundle.json"
> ```
非常感谢，之前有试过用mv，但是还是报错了，原来路径的写法和在windows环境下也不一样，谢谢你！
