### ISSUE TITLE
路由下刷新页面报错

### ISSUE THREAD

**Issue by zhanghanbing1998** [lentoo/vue-cli-ssr-example#17]
路由：http://localhost:3000/list
刷新页面报以下错误：ENOENT: no such file or directory, stat '/Users/zhanghanbing/WebstormProjects/www.jiangzi.com/dist/list'

**Comment by mythbobo** [comment]
直接clone后发现同样的问题。首页生成了html代码。但是about页面也出现了

  | ENOENT: no such file or directory, stat 'C:\ssrdemo\vue-cli-ssr-example\dist\about'
-- | --
