### ISSUE TITLE
如何运行服务端代码？

### ISSUE THREAD

**Issue by coderYyz** [lentoo/vue-cli-ssr-example#3]
node ./server/ssr.js 也是报错

**Comment by lentoo** [comment]
development模式的话先运行 npm run server 然后在启动另一个窗口运行 npm run dev:serve

**Comment by xdwxls** [comment]
@lentoo 那如何部署到服务器上呢，步骤是如何的

**Comment by lentoo** [comment]
npm run build:win 然后可以通过ip地址访问，也可以通过nginx转发

**Comment by xdwxls** [comment]
@lentoo 大佬能否qq 告知下，具体我请教下

**Comment by lentoo** [comment]
加我v吧 18529202749
