### ISSUE TITLE
npm run build:win  move ?

### ISSUE THREAD

**Issue by VanquisherMe** [lentoo/vue-cli-ssr-example#5]
![image](https://user-images.githubusercontent.com/4927398/50907403-3f212c80-1462-11e9-9fb8-a1f32350b910.png)

**Comment by lentoo** [comment]
你的是mac？尝试下把 move 改成 mv

**Comment by VanquisherMe** [comment]
![image](https://user-images.githubusercontent.com/4927398/51193204-41ccc780-1923-11e9-92a8-250ed03c0aef.png)
嗯 mv 貌似没用 修改成这样处理
清除dist 文件，并且将两次服务bundle 放入 dsit，
另外想请教一下
![image](https://user-images.githubusercontent.com/4927398/51193487-f0710800-1923-11e9-902a-1d1eec2e78e0.png)
bundle 在这里的含义，是win 的语法？

**Comment by lentoo** [comment]
并不是，这个bundle是将 dist/vue-ssr-server-bundle.json 重命名为 bundle
