### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by VanquisherMe** [lentoo/vue-cli-ssr-example#6]
![image](https://user-images.githubusercontent.com/4927398/51258448-ff6bbf00-19e4-11e9-9db5-6c30a04c76d9.png)

![image](https://user-images.githubusercontent.com/4927398/51258726-9afd2f80-19e5-11e9-9808-53ae5f76749a.png)
![image](https://user-images.githubusercontent.com/4927398/51258852-dd267100-19e5-11e9-9c40-8ad06ecc2525.png)
开发环境正常的，生产环境访问会出现这样的问题
[vue ssr document is not defined](https://github.com/vuejs/vue-router/issues/2380)
[https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90)

我尝试使用里面的方案去修复但是没有成功
希望能够关注

**Comment by lentoo** [comment]
在vue.config.js中，添加 
css:{
  extract:false
}

**Comment by lentoo** [comment]
没尝试过这个方案，不好意思，帮不了你
